name: hybrid_app
description: Mootorratta-orienteerumise rakendus.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.5+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^2.0.0
  shared_preferences: 0.4.3
  path_provider: ^0.4.1
  uuid: 1.0.3
  barcode_scan:
    git:
      url: https://github.com/Crimsons/flutter_barcode_reader.git
      ref: qr_codes
  crypto: ^2.0.6
  intl: 0.15.7
  uptime: ^0.0.1
  vibration: 1.0.2
  flutter_email_sender:
    git:
      url: https://github.com/Crimsons/flutter_email_sender.git
      ref: fix


dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
